version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config:/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    depends_on:
      - api_server
    restart: always
    networks:
      prom_net:
        ipv4_address: 172.28.1.1

  api_server:
    build: .
    ports:
      - 8000:8000
    restart: always
    networks:
      prom_net:
        ipv4_address: 172.28.1.2


networks:
  prom_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16