# prometheus global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: api_server
    scrape_interval: 5s
    static_configs:
    - targets: ['api_server:8000']
